"$schema" = "https://schema.tauri.app/config/2"

productName = "echozone"
version = "0.1.0"
identifier = "com.echozone.app"

[build]
beforeDevCommand = "npm run dev"
devUrl = "http://localhost:1420"
beforeBuildCommand = "npm run build"
frontendDist = "../dist"

[[app.windows]]
label = "player"
title = "echozone"
width = 418
height = 647
resizable = true
fullscreen = false
decorations = false
transparent = true

[app.security]
csp = ""

[bundle]
active = true
resources = ["bin/yt-dlp.exe"]
icon = [
  "icons/32x32.png",
  "icons/128x128.png",
  "icons/128x128@2x.png",
  "icons/icon.icns",
  "icons/icon.ico"
]
